channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1 
  - pip:
    - rpaframework==28.5.1 
    - pyyaml==6.0.1
    - requests==2.31.0
