website_url: https://www.nytimes.com
search_phrase: Artificial Intelligence
news_category: Technology
num_months: 6
output_directory: output
excel_file_name: nytimes_articles.xlsx
log_file_path: logs/news_extractor.log
log_level: INFO
browser_name: chrome
headless_mode: true