tasks:
  Run Task:
    shell: python main.py

environmentConfigs:
  - environment_windows_amd64_freeze.yaml
  - environment_linux_amd64_freeze.yaml
  - environment_darwin_amd64_freeze.yaml
  - conda.yaml

artifactsDir: output

PATH:
 - .

PYTHONPATH:
  - .

ignoreFiles:
  - .gitignore